name: Run Hello DevOps Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run script
        run: |
          chmod +x hello_devops.sh
          ./hello_devops.sh

      - name: Run tests
        run: |
          chmod +x test_hello_devops.sh
          ./test_hello_devops.sh

